services:
  - type: web
    name: arcane-2k25-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASS
        sync: false